# Generated by Django 4.0.6 on 2022-07-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed', '-date']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
